runtime: python312

handlers:
- url: /projects
  static_dir: projects

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /templates
  static_dir: templates

- url: /loc
  static_dir: loc

- url: /library
  static_dir: library

- url: /.*
  script: main.py